#!/bin/bash

# Overlay-Network-Manager
# Copyright (C) 2010 Fokus Fraunhofer <Julian.Vetter@fokus.fraunhofer.de>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

DIR=`pwd`
FPATTERN=$1

if test -z $1
then    
    echo "Usage: ipfixfromfile filepattern [col_ipaddr] [port]"
    exit
fi

# Check if port/url is set from commandline, if not set to default
if test -z $2
then
    URL="127.0.0.1"
else
    URL=$2
fi

if test -z $3
then
    PORT=4739
else
    PORT=$3
fi

for file in $FPATTERN*;
do
    echo $file
    `nc $URL $PORT < $file`
done

